name: Run integration tests on microk8s
on:
  push:
    branches:
      - main
jobs:
  run-integration:
    name: run-integration on ${{ matrix.k8s-release }}
    strategy:
      max-parallel: 48
      fail-fast: true
      matrix:
        k8s-release: [ 1.20/stable ] #, 1.19/stable, 1.18/stable ]
    runs-on: ubuntu-latest
    steps:
      - name: Configure LXD
        run: |
          sudo snap install lxd
          sudo lxd.migrate -yes || true
          sudo lxd waitready
          sudo lxd init --auto
          sudo usermod -a -G lxd ${USER}
          sudo groupadd --force --system lxd
          sudo usermod --append --groups lxd ${USER}
          newgrp lxd
          sudo newgrp lxd
          sudo systemctl start snap.lxd.daemon.service
          sudo systemctl status snap.lxd.daemon.service
          sudo systemctl start snap.lxd.daemon.unix.socket
          sudo systemctl status snap.lxd.daemon.unix.socket
          sudo chmod 0777 /var/snap/lxd/common/lxd/unix.socket

      - name: Checkout code
        uses: actions/checkout@v2

#      - uses: hashicorp/setup-terraform@v1
#        with:
#          cli_config_credentials_hostname: 'app.terraform.io'
#          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: terraform/microk8s/

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: terraform/microk8s/

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: terraform/microk8s/

      - name: Terraform Apply
        id: apply
        run: |
          newgrp lxd
          terraform apply -input=false -auto-approve -var k8s-version=${{ env.k8s_release }}
        working-directory: terraform/microk8s/
        env:
          k8s_release: ${{ matrix.k8s-release }}

      - run: lxc exec mk8s-node-integration-0 -- microk8s enable dns
      - run: lxc exec mk8s-node-integration-0 -- microk8s enable storage

      - uses: actions/setup-go@v2
        with:
          go-version: '1.15' # The Go version to download (if necessary) and use.

      - uses: azure/setup-helm@v1
        id: install

      - run: go mod download
        working-directory: integration/

      - run: go test -v
        working-directory: integration/